export const t = {
  ro: {
    nav: { title: "Casa din Țicău", apts: "Apartamente", contact: "Contact", lang: "EN" },
    hero: {
      tag: "Cazare de calitate · Iași",
      heading: "Un loc ca acasă",
      sub: "7 apartamente complet utilate, disponibile pentru sejururi scurte sau lungi",
      cta: "Vezi apartamentele",
    },
    features: [
      { icon: "🏠", title: "7 apartamente", desc: "De la studio la penthouse, pentru orice nevoie" },
      { icon: "📍", title: "Locație centrală", desc: "În inima Iașului, aproape de tot ce contează" },
      { icon: "✨", title: "Complet utilat", desc: "Bucătărie, WiFi, AC și tot ce ai nevoie" },
      { icon: "📞", title: "Suport 24/7", desc: "Suntem mereu disponibili pentru tine" },
    ],
    section: "Apartamentele noastre",
    sectionSub: "Alege apartamentul perfect pentru sejurul tău",
    sectionLabel: "Cazare",
    card: { from: "de la", night: "/noapte", guests: "pers.", sqm: "mp", floor: "Etaj", book: "Rezervă acum", popular: "Popular", details: "Vezi detalii" },
    modal: {
      title: "Rezervare",
      name: "Nume complet", email: "Email", phone: "Telefon",
      checkin: "Check-in", checkout: "Check-out", guests: "Nr. persoane",
      message: "Mesaj (opțional)",
      send: "Trimite rezervarea", cancel: "Anulează",
      success: "Rezervare trimisă!", successSub: "Vă vom contacta în curând pentru confirmare.",
    },
    contact: {
      label: "Contact",
      heading: "Ia legătura cu noi",
      sub: "Suntem aici să te ajutăm să găsești cazarea perfectă",
      addr: "Strada Exemplu nr. 10, Iași",
      copy: "© 2025 Casa din Țicău · Toate drepturile rezervate",
    },
    aptPage: {
      back: "Înapoi la apartamente",
      overview: "Prezentare generală",
      amenities: "Dotări",
      location: "Locație",
      bookThis: "Rezervă acest apartament",
      priceFrom: "de la",
      perNight: "/noapte",
      floor: "Etaj",
      guests: "Oaspeți max.",
      surface: "Suprafață",
      description: "Descriere",
    },
  },
  en: {
    nav: { title: "Casa din Țicău", apts: "Apartments", contact: "Contact", lang: "RO" },
    hero: {
      tag: "Quality accommodation · Iași",
      heading: "A home away from home",
      sub: "7 fully equipped apartments, available for short or long stays",
      cta: "View apartments",
    },
    features: [
      { icon: "🏠", title: "7 apartments", desc: "From studio to penthouse, for every need" },
      { icon: "📍", title: "Central location", desc: "In the heart of Iași, close to everything" },
      { icon: "✨", title: "Fully equipped", desc: "Kitchen, WiFi, AC and everything you need" },
      { icon: "📞", title: "24/7 support", desc: "We're always available for you" },
    ],
    section: "Our apartments",
    sectionSub: "Choose the perfect apartment for your stay",
    sectionLabel: "Accommodation",
    card: { from: "from", night: "/night", guests: "guests", sqm: "sqm", floor: "Floor", book: "Book now", popular: "Popular", details: "View details" },
    modal: {
      title: "Reservation",
      name: "Full name", email: "Email", phone: "Phone",
      checkin: "Check-in", checkout: "Check-out", guests: "Guests",
      message: "Message (optional)",
      send: "Send reservation", cancel: "Cancel",
      success: "Reservation sent!", successSub: "We'll contact you shortly to confirm.",
    },
    contact: {
      label: "Contact",
      heading: "Get in touch",
      sub: "We're here to help you find the perfect accommodation",
      addr: "Strada Exemplu nr. 10, Iași",
      copy: "© 2025 Casa din Țicău · All rights reserved",
    },
    aptPage: {
      back: "Back to apartments",
      overview: "Overview",
      amenities: "Amenities",
      location: "Location",
      bookThis: "Book this apartment",
      priceFrom: "from",
      perNight: "/night",
      floor: "Floor",
      guests: "Max. guests",
      surface: "Surface",
      description: "Description",
    },
  },
};

export const apartments = [
  {
    id: 1,
    slug: "studio-compact",
    name: { ro: "Studio Compact", en: "Compact Studio" },
    price: 45, sqm: 32, maxGuests: 2, floor: 1,
    img: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80",
      "https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=900&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=900&q=80",
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=900&q=80",
    ],
    tags: ["WiFi", "AC", "Smart TV"],
    popular: false,
    description: {
      ro: "Un studio compact și modern, perfect pentru cupluri sau călători singuri. Complet mobilat cu bucătărie echipată, baie modernă și zonă de living confortabilă. Situat la etajul 1, oferă acces facil și o atmosferă liniștită.",
      en: "A compact and modern studio, perfect for couples or solo travelers. Fully furnished with an equipped kitchen, modern bathroom, and comfortable living area. Located on the 1st floor, it offers easy access and a peaceful atmosphere.",
    },
  },
  {
    id: 2,
    slug: "garsoniera-deluxe",
    name: { ro: "Garsonieră Deluxe", en: "Deluxe Studio" },
    price: 55, sqm: 38, maxGuests: 2, floor: 2,
    img: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=80",
      "https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?w=900&q=80",
      "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=900&q=80",
    ],
    tags: ["WiFi", "AC", "Parcare"],
    popular: false,
    description: {
      ro: "O garsonieră spațioasă cu finisaje premium, ideală pentru sejururi de afaceri sau relaxare. Include loc de parcare dedicat, bucătărie complet utilată și un spațiu de dormit generos.",
      en: "A spacious studio with premium finishes, ideal for business stays or relaxation. Includes a dedicated parking spot, fully equipped kitchen, and a generous sleeping area.",
    },
  },
  {
    id: 3,
    slug: "apartament-2-camere",
    name: { ro: "Apartament 2 Camere", en: "2-Room Apartment" },
    price: 70, sqm: 52, maxGuests: 3, floor: 1,
    img: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=900&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=80",
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=900&q=80",
    ],
    tags: ["WiFi", "AC", "Balcon"],
    popular: true,
    description: {
      ro: "Apartamentul nostru cel mai popular, cu 2 camere separate — living spațios și dormitor confortabil. Balconul oferă o priveliște frumoasă a orașului. Perfect pentru familii mici sau cupluri care doresc mai mult spațiu.",
      en: "Our most popular apartment, with 2 separate rooms — spacious living room and comfortable bedroom. The balcony offers a beautiful city view. Perfect for small families or couples wanting more space.",
    },
  },
  {
    id: 4,
    slug: "2-camere-premium",
    name: { ro: "2 Camere Premium", en: "Premium 2-Room" },
    price: 85, sqm: 58, maxGuests: 4, floor: 3,
    img: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80",
      "https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=900&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=80",
      "https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?w=900&q=80",
    ],
    tags: ["WiFi", "AC", "Balcon", "Smart TV"],
    popular: false,
    description: {
      ro: "Varianta premium a apartamentului cu 2 camere, cu finisaje superioare și mobilier de calitate. Smart TV în fiecare cameră, bucătărie complet echipată și un balcon generos la etajul 3.",
      en: "The premium version of our 2-room apartment, with superior finishes and quality furniture. Smart TV in each room, fully equipped kitchen, and a generous balcony on the 3rd floor.",
    },
  },
  {
    id: 5,
    slug: "apartament-3-camere",
    name: { ro: "Apartament 3 Camere", en: "3-Room Apartment" },
    price: 100, sqm: 75, maxGuests: 5, floor: 2,
    img: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=900&q=80",
      "https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=900&q=80",
      "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=900&q=80",
    ],
    tags: ["WiFi", "AC", "Balcon", "Parcare"],
    popular: true,
    description: {
      ro: "Spațios și luminos, cu 3 camere separate — ideal pentru familii sau grupuri. Include loc de parcare, balcon mare și două băi. Bucătăria complet utilată face sejurul și mai confortabil.",
      en: "Spacious and bright, with 3 separate rooms — ideal for families or groups. Includes parking, a large balcony, and two bathrooms. The fully equipped kitchen makes the stay even more comfortable.",
    },
  },
  {
    id: 6,
    slug: "penthouse-junior",
    name: { ro: "Penthouse Junior", en: "Junior Penthouse" },
    price: 130, sqm: 90, maxGuests: 4, floor: 5,
    img: "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=900&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=80",
      "https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?w=900&q=80",
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=900&q=80",
    ],
    tags: ["WiFi", "AC", "Terasă", "Jacuzzi"],
    popular: false,
    description: {
      ro: "Un penthouse elegant la etajul 5, cu terasă privată și jacuzzi. Priveliște panoramică asupra orașului, finisaje de lux și o atmosferă exclusivistă pentru o experiență de neuitat.",
      en: "An elegant penthouse on the 5th floor, with a private terrace and jacuzzi. Panoramic city views, luxury finishes, and an exclusive atmosphere for an unforgettable experience.",
    },
  },
  {
    id: 7,
    slug: "penthouse-panoramic",
    name: { ro: "Penthouse Panoramic", en: "Panoramic Penthouse" },
    price: 180, sqm: 120, maxGuests: 6, floor: 6,
    img: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=900&q=80",
      "https://images.unsplash.com/photo-1630699144867-37acec97df5a?w=900&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=80",
    ],
    tags: ["WiFi", "AC", "Terasă", "Jacuzzi", "Parcare"],
    popular: false,
    description: {
      ro: "Cel mai exclusivist apartament, cu 120mp de lux absolut. Terasă enormă cu jacuzzi, priveliște panoramică la 360°, parcare privată și dotări premium. Experiența supremă de cazare în Iași.",
      en: "The most exclusive apartment, with 120sqm of absolute luxury. Huge terrace with jacuzzi, 360° panoramic views, private parking, and premium amenities. The ultimate accommodation experience in Iași.",
    },
  },
];
